//
//  GameBoardViewModelCreator.swift
//  Roshambo
//
//  Created Christian Elies on 24.04.19.
//  Copyright © 2019 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import Foundation

protocol GameBoardViewModelCreatorProvider {
	var gameBoardViewModelCreator: GameBoardViewModelCreatorProtocol { get }
}

protocol GameBoardViewModelCreatorProtocol {
    func createViewModel(forPlayerViewState playerViewState: PlayerViewState, computerViewState: PlayerViewState, winnerRoshambo: Roshambo?) -> GameBoardViewViewModel
}

final class GameBoardViewModelCreator {
	private let dependencies: GameBoardViewModelCreatorDependenciesProtocol

	init(dependencies: GameBoardViewModelCreatorDependenciesProtocol) {
		self.dependencies = dependencies
	}
}

extension GameBoardViewModelCreator: GameBoardViewModelCreatorProtocol {
    func createViewModel(forPlayerViewState playerViewState: PlayerViewState, computerViewState: PlayerViewState, winnerRoshambo: Roshambo?) -> GameBoardViewViewModel {
        var isPlayerWinner = false
        var isComputerWinner = false
        var gameResult: GameResult = .none
        
        if case let PlayerViewState.result(playerRoshambo) = playerViewState,
            case PlayerViewState.result(_) = computerViewState {
            if let winnerRoshambo = winnerRoshambo {
                isPlayerWinner = playerRoshambo == winnerRoshambo
                isComputerWinner = !isPlayerWinner
                gameResult = isPlayerWinner ? .playerWins : .computerWins
            } else {
                gameResult = .draw
            }
        }
        
        let playerViewViewModel = dependencies.playerViewViewModelCreator.createViewModel(forState: playerViewState,
                                                                                          isWinner: isPlayerWinner)
        let gameResultViewViewModel = GameResultViewViewModel(gameResult: gameResult)
        let computerViewViewModel = dependencies.playerViewViewModelCreator.createViewModel(forState: computerViewState,
                                                                                            isWinner: isComputerWinner)
        return GameBoardViewViewModel(playerViewViewModel: playerViewViewModel,
                                      gameResultViewViewModel: gameResultViewViewModel,
                                      computerViewViewModel: computerViewViewModel)
    }
}
