//
//  GameBoardViewModelCreatorFactory.swift
//  Roshambo
//
//  Created Christian Elies on 24.04.19.
//  Copyright © 2019 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import Foundation

protocol GameBoardViewModelCreatorFactoryProtocol {
	static func makeGameBoardViewModelCreator() -> GameBoardViewModelCreatorProtocol
}

final class GameBoardViewModelCreatorFactory: GameBoardViewModelCreatorFactoryProtocol {
	static func makeGameBoardViewModelCreator() -> GameBoardViewModelCreatorProtocol {
		let dependencies = GameBoardViewModelCreatorDependencies()
		return GameBoardViewModelCreator(dependencies: dependencies)
	}
}
