# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

price_tier 0

app_review_information(
                       first_name: "Christian",
                       last_name: "Elies",
                       phone_number: "N/A",
                       email_address: "chris.elies13@gmail.com",
                       demo_user: "N/A",
                       demo_password: "N/A",
                       notes: "No demo account needed"
)

submission_information({
                        export_compliance_encryption_updated: false,
                        export_compliance_uses_encryption: false,
                        content_rights_contains_third_party_content: false,
                        add_id_info_uses_idfa: false
})

automatic_release false

app_icon './fastlane/metadata/AppIcon.png'

app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"
