# A list of devices you want to take the screenshots from
devices([
    "iPhone Xs Max",
    "iPhone 6s Plus",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
    "en-US",
    "de-DE"
])

# The name of the scheme which contains the UI Tests
scheme("Take Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# For more information about all available options run
# fastlane action snapshot

# Latest version of iOS
ios_version '11.0'
