//
//  GameBoardRouter.swift
//  Roshambo
//
//  Created Christian Elies on 24.04.19.
//  Copyright © 2019 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import UIKit

protocol GameBoardRouterProtocol {
    func dismiss(animated: Bool)
}

final class GameBoardRouter {
    private let dependencies: GameBoardRouterDependenciesProtocol
    private weak var viewController: UIViewController?

    init(dependencies: GameBoardRouterDependenciesProtocol,
    	 viewController: UIViewController?) {
        self.dependencies = dependencies
        self.viewController = viewController
    }
}

extension GameBoardRouter: GameBoardRouterProtocol {
	func dismiss(animated: Bool) {
		viewController?.dismiss(animated: animated, completion: nil)
	}
}
