//
//  GameBoardPresenterDependencies.swift
//  Roshambo
//
//  Created Christian Elies on 24.04.19.
//  Copyright © 2019 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//  https://www.christianelies.de
//

import Foundation

protocol GameBoardPresenterDependenciesProtocol: GameBoardViewModelCreatorProvider {
    
}

struct GameBoardPresenterDependencies: GameBoardPresenterDependenciesProtocol {
    let gameBoardViewModelCreator: GameBoardViewModelCreatorProtocol
    
    init() {
        gameBoardViewModelCreator = GameBoardViewModelCreatorFactory.makeGameBoardViewModelCreator()
    }
}
