//
//  GameResultServiceSpec.swift
//  Roshambo
//
//  Created Christian Elies on 24.04.19.
//  Copyright © 2019 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

@testable import Roshambo
import Nimble
import Quick
import UIKit

final class GameResultServiceSpec: QuickSpec {
	override func spec() {
		describe("GameResultService") {
			context("when ...") {
				it("should ...") {

				}
			}
		}
	}
}
