//
//  PlayerViewViewModelCreator.swift
//  Roshambo
//
//  Created Christian Elies on 24.04.19.
//  Copyright © 2019 Christian Elies. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import UIKit

protocol PlayerViewViewModelCreatorProvider {
	var playerViewViewModelCreator: PlayerViewViewModelCreatorProtocol { get }
}

protocol PlayerViewViewModelCreatorProtocol {
    func createViewModel(forState state: PlayerViewState, isWinner: Bool) -> PlayerViewViewModel
}

final class PlayerViewViewModelCreator {
	private let dependencies: PlayerViewViewModelCreatorDependenciesProtocol

	init(dependencies: PlayerViewViewModelCreatorDependenciesProtocol) {
		self.dependencies = dependencies
	}
}

extension PlayerViewViewModelCreator: PlayerViewViewModelCreatorProtocol {
    func createViewModel(forState state: PlayerViewState, isWinner: Bool) -> PlayerViewViewModel {
        switch state {
            case .initial:
                return PlayerViewViewModel(isInformationLabelHidden: false,
                                           informationLabelText: "You first 😉",
                                           informationLabelFontSize: 17,
                                           areActionButtonsHidden: true)
            case .takeAction:
                return PlayerViewViewModel(isInformationLabelHidden: true,
                                           informationLabelText: "",
                                           informationLabelFontSize: 28,
                                           areActionButtonsHidden: false)
            case .result(let roshambo):
                let informationLabelFontSize: CGFloat = isWinner ? 72 : 28
                return PlayerViewViewModel(isInformationLabelHidden: false,
                                           informationLabelText: roshambo.displayText,
                                           informationLabelFontSize: informationLabelFontSize,
                                           areActionButtonsHidden: true)
        }
    }
}
